export const START_FETCHING_DAILY_WEATHER = 'START_FETCHING_DAILY_WEATHER';
export const FETCH_DAILY_WEATHER_SUCCEEDED = 'FETCH_DAILY_WEATHER_SUCCEEDED';
export const FETCH_DAILY_WEATHER_FAILED = 'FETCH_DAILY_WEATHER_FAILED';

export const START_FETCHING_CURRENT_WEATHER = 'START_FETCHING_CURRENT_WEATHER';
export const FETCH_CURRENT_WEATHER_SUCCEEDED = 'FETCH_CURRENT_WEATHER_SUCCEEDED';
export const FETCH_CURRENT_WEATHER_FAILED = 'FETCH_CURRENT_WEATHER_FAILED';

