export const START_FETCHING_WEATHER_DAILY = 'START_FETCHING_WEATHER_DAILY';
export const FETCH_WEATHER_DAILY_SUCCEEDED = 'FETCH_WEATHER_DAILY_SUCCEEDED';
export const FETCH_WEATHER_DAILY_FAILED = 'FETCH_WEATHER_DAILY_FAILED';

